<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AssemblyName>HateVPN.Setup</AssemblyName>
    <Version>1.0.13</Version>
    <Product>HateVPN Setup</Product>
    <ApplicationIcon>../HateVPN.Desktop/Assets/HateVPN.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Resource Include="../HateVPN.Desktop/Assets/HateVPN.ico" Link="Assets/HateVPN.ico" />
    <Resource Include="Assets/installer-background.png" />
    <EmbeddedResource Include="Assets/installer-video.mp4" LogicalName="HateVPN.Setup.Video.mp4" />
    <EmbeddedResource Include="../../dist/HateVPN-1.0-x64.msi" LogicalName="HateVPN.Setup.Payload.msi" />
  </ItemGroup>
</Project>
